// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEej-vstH_ap0ZUbQqWUYbs1W0RZ48CFI',
    appId: '1:287791746485:web:3258b4878d750298325dfc',
    messagingSenderId: '287791746485',
    projectId: 'firebasecapstone',
    authDomain: 'fir-capstone-a8aa7.firebaseapp.com',
    storageBucket: 'firebasecapstone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa5NUI6H35gMOD555Jb4UJaIrXD6HLgS4',
    appId: '1:287791746485:android:63e4cdc6f16c6387325dfc',
    messagingSenderId: '287791746485',
    projectId: 'firebasecapstone',
    storageBucket: 'firebasecapstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy6Q28dI5e0ItsyL9_ZMmGHuJ-G_CLZvs',
    appId: '1:287791746485:ios:c86ecff0b08f2f1a325dfc',
    messagingSenderId: '287791746485',
    projectId: 'firebasecapstone',
    storageBucket: 'firebasecapstone.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy6Q28dI5e0ItsyL9_ZMmGHuJ-G_CLZvs',
    appId: '1:287791746485:ios:c86ecff0b08f2f1a325dfc',
    messagingSenderId: '287791746485',
    projectId: 'firebasecapstone',
    storageBucket: 'firebasecapstone.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEej-vstH_ap0ZUbQqWUYbs1W0RZ48CFI',
    appId: '1:287791746485:web:2195015cfe942582325dfc',
    messagingSenderId: '287791746485',
    projectId: 'firebasecapstone',
    authDomain: 'fir-capstone-a8aa7.firebaseapp.com',
    storageBucket: 'firebasecapstone.firebasestorage.app',
  );
}
